import { MadlibPart } from '@/types';
import { nanoid } from 'nanoid';

export const madlibStructure: MadlibPart[] = [
  {
    id: nanoid(11),
    type: 'heading',
    value: 'Customize your prompt',
  },
  {
    id: nanoid(11),
    type: 'text',
    value:
      'I heard the Canadian government is running a public policy consultation aimed at regulating AI in Canada.',
  },
  {
    id: nanoid(11),
    type: 'text', //
    value: 'I need help crafting a letter to participate in this consultation.',
  },
  {
    id: nanoid(11),
    type: 'text', //
    value: 'My name is',
  },
  {
    id: nanoid(11),
    type: 'input',
    name: 'person_name',
    placeholder: 'insert name',
    value: '',
  },
  { id: nanoid(11), type: 'text', value: '.' },
  { id: nanoid(11), type: 'text', value: 'I am a' },
  {
    id: nanoid(11),
    type: 'input',
    name: 'age',
    placeholder: 'insert age',
    value: '',
  },
  { id: nanoid(11), type: 'text', value: 'years old' },
  {
    id: nanoid(11),
    type: 'input',
    name: 'profession',
    placeholder: 'insert profession',
    value: '',
  },
  {
    id: nanoid(11),
    type: 'text',
    value: 'from',
  },
  {
    id: nanoid(11),
    type: 'input',
    name: 'location',
    placeholder: 'insert location',
    value: '',
  },
  {
    id: nanoid(11),
    type: 'text',
    value: '.',
  },
  {
    id: nanoid(11),
    type: 'text',
    value: 'I am',
  },
  {
    id: nanoid(11),
    type: 'input',
    name: 'emotion',
    placeholder: 'insert emotion or feeling',
    value: '',
  },
  { id: nanoid(11), type: 'input', name: 'issue1', placeholder: 'issue', value: '' },
  { id: nanoid(11), type: 'text', value: 'and' },
  { id: nanoid(11), type: 'input', name: 'issue2', placeholder: 'issue', value: '' },
  {
    id: nanoid(11),
    type: 'text',
    value: '.',
  },
  {
    id: nanoid(11),
    type: 'text',
    value:
      'Please draft a letter to the committee chair using these details and expressing how Canada should regulate AI accordingly.',
  },
  {
    id: nanoid(11),
    type: 'heading',
    value: 'Customize your writing style ',
  },
  {
    id: nanoid(11),
    type: 'text',
    value: 'Please write in a',
  },
  {
    id: nanoid(11),
    type: 'select',
    name: 'tone',
    options: ['humble', 'respectful', 'civil', 'concerned', 'aggressive'],
    value: 'respectful',
  },
  { id: nanoid(11), type: 'text', value: 'tone and in a' },
  {
    id: nanoid(11),
    type: 'select',
    name: 'tone',
    options: ['formal', 'informal', 'academic', 'slang', 'polite', 'silly'],
    value: 'formal',
  },
  { id: nanoid(11), type: 'text', value: 'style.' },
  { id: nanoid(11), type: 'text', value: 'The letter should contain at least' },
  {
    id: nanoid(11),
    type: 'select',
    name: 'size',
    options: ['1', '2', '3', '4', '5'],
    value: '3',
  },
  { id: nanoid(11), type: 'text', value: 'paragraphs.' },
];

export const madlibStructureV1: MadlibPart[] = [
  {
    id: nanoid(11),
    type: 'heading',
    value: 'Introduction ',
  },
  { id: nanoid(11), type: 'text', value: 'My name is' },
  {
    id: nanoid(11),
    type: 'input',
    name: 'person_name',
    placeholder: 'insert name',
    value: '',
  },
  { id: nanoid(11), type: 'text', value: '. I am a' },
  {
    id: nanoid(11),
    type: 'input',
    name: 'age',
    placeholder: 'insert age',
    value: '',
  },
  { id: nanoid(11), type: 'text', value: 'years old' },
  {
    id: nanoid(11),
    type: 'input',
    name: 'profession',
    placeholder: 'insert profession',
    value: '',
  },
  {
    id: nanoid(11),
    type: 'text',
    value: 'from',
  },
  {
    id: nanoid(11),
    type: 'input',
    name: 'location',
    placeholder: 'insert location',
    value: '',
  },
  {
    id: nanoid(11),
    type: 'text',
    value: '. I am',
  },
  {
    id: nanoid(11),
    type: 'select',
    name: 'choice1',
    options: ['very concerned', 'very confused', 'neutral', 'very excited'],
    value: 'neutral',
  },
  {
    id: nanoid(11),
    type: 'text',
    value:
      'about AI technologies. I heard the Canadian government is running a public policy consultation aimed at regulating AI in Canada. I need help crafting a letter to participate in this consultation.',
  },
  {
    id: nanoid(11),
    type: 'heading',
    value: 'Opinions ',
  },
  {
    id: nanoid(11),
    type: 'text',
    value:
      'Please help me write a letter to the committee chair. Please express my strong opinions',
  },
  {
    id: nanoid(11),
    type: 'select',
    name: 'choice2',
    options: ['in favor', 'indifferent to', 'against'],
    value: 'indifferent to',
  },
  { id: nanoid(11), type: 'text', value: 'the use of AI for' },
  { id: nanoid(11), type: 'input', name: 'issue1', placeholder: 'issue', value: '' },
  { id: nanoid(11), type: 'text', value: 'and' },
  { id: nanoid(11), type: 'input', name: 'issue2', placeholder: 'issue', value: '' },
  { id: nanoid(11), type: 'text', value: '. Please emphasize the' },
  {
    id: nanoid(11),
    type: 'select',
    name: 'choice3',
    options: ['dangerous', 'catastrophic', 'positive', 'beneficial', 'nonsensical'],
    value: 'nonsensical',
  },
  { id: nanoid(11), type: 'text', value: 'impact of AI for' },
  { id: nanoid(11), type: 'input', name: 'issue3', placeholder: 'issue', value: '' },
  { id: nanoid(11), type: 'text', value: 'and' },
  { id: nanoid(11), type: 'input', name: 'issue4', placeholder: 'issue', value: '' },
  { id: nanoid(11), type: 'text', value: '. Lastly, I wanted to mention the' },
  {
    id: nanoid(11),
    type: 'select',
    name: 'choice4',
    options: ['relief', 'prosperity', 'harm', 'confusion'],
    value: 'confusion',
  },
  { id: nanoid(11), type: 'text', value: 'it can cause to' },
  { id: nanoid(11), type: 'input', name: 'group1', placeholder: 'group', value: '' },
  { id: nanoid(11), type: 'text', value: 'and' },
  { id: nanoid(11), type: 'input', name: 'group2', placeholder: 'group', value: '' },
  { id: nanoid(11), type: 'text', value: '.' },
  {
    id: nanoid(11),
    type: 'heading',
    value: 'Tone & Style ',
  },
  { id: nanoid(11), type: 'text', value: 'Please write in a' },
  {
    id: nanoid(11),
    type: 'select',
    name: 'tone',
    options: ['humble', 'respectful', 'civil', 'concerned', 'aggressive'],
    value: 'respectful',
  },
  { id: nanoid(11), type: 'text', value: 'tone and in an' },
  {
    id: nanoid(11),
    type: 'select',
    name: 'tone',
    options: ['formal', 'informal', 'academic', 'slang', 'polite', 'silly'],
    value: 'formal',
  },
  { id: nanoid(11), type: 'text', value: '. Please write at least' },
  {
    id: nanoid(11),
    type: 'select',
    name: 'size',
    options: ['three', 'four', 'five', 'six'],
    value: 'five',
  },
  { id: nanoid(11), type: 'text', value: 'paragraphs.' },
];
